min_mainnet_k_size: 32
ping_interval: 120
self_hostname: &self_hostname "localhost"
daemon_port: 18574
daemon_max_message_size: 50000000
inbound_rate_limit_percent: 100
outbound_rate_limit_percent: 30
network_overrides: &network_overrides
  constants:
    mainnet:
      NETWORK_TYPE: 0
      GENESIS_CHALLENGE: cd712de5a54aa420613d90b4c0f7ad28de3ca1f3edef0ef3fe12d2721c067802
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "86f83e6488b1ab859e3ce5beb6fca3dec3ee2f9b0e01d57605cc61da72aeb195"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "d34204e34e9ca9440cfa9bf66d3bef14e954a78733e09d5b8e536060916588d3"
    testnet1:
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      GENESIS_CHALLENGE: 6446dcf4b3a494125febab1933e07caf60cbffe280e1311556386322b2091458
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: d34204e34e9ca9440cfa9bf66d3bef14e954a78733e09d5b8e536060916588d3
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: 86f83e6488b1ab859e3ce5beb6fca3dec3ee2f9b0e01d57605cc61da72aeb195
      MIN_PLOT_SIZE: 18
      NETWORK_TYPE: 1
      MEMPOOL_BLOCK_BUFFER: 50
      EPOCH_BLOCKS: 768
      DIFFICULTY_STARTING: 30
  config:
    mainnet:
      address_prefix: "xslv"
      default_full_node_port: 18520
    testnet1:
      address_prefix: "txslv"
      default_full_node_port: 17854
selected_network: &selected_network "mainnet"
ALERTS_URL: https://download.salvianetwork.net/notify/mainnet_alert.txt
CHIA_ALERTS_PUBKEY: 89b7fd87cb56e926ecefb879a29aae308be01f31980569f6a75a69d2a9a69daefd71fb778d865f7c50d6c967e3025937
private_ssl_ca:
  crt: "config/ssl/ca/private_ca.crt"
  key: "config/ssl/ca/private_ca.key"
salvia_ssl_ca:
  crt: "config/ssl/ca/salvia_ca.crt"
  key: "config/ssl/ca/salvia_ca.key"
daemon_ssl:
  private_crt: "config/ssl/daemon/private_daemon.crt"
  private_key: "config/ssl/daemon/private_daemon.key"
logging: &logging
  log_stdout: False
  log_filename: "log/debug.log"
  log_level: "WARNING"
  log_maxfilesrotation: 7
  log_syslog: False
  log_syslog_host: "localhost"
  log_syslog_port: 514
harvester:
  port: 18524
  farmer_peer:
    host: *self_hostname
    port: 18523
  start_rpc_server: True
  rpc_port: 18541
  num_threads: 30
  plots_refresh_parameter:
    interval_seconds: 120
    retry_invalid_seconds: 1200
    batch_size: 300
    batch_sleep_milliseconds: 1
  parallel_read: True
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  plot_directories: []
  ssl:
    private_crt: "config/ssl/harvester/private_harvester.crt"
    private_key: "config/ssl/harvester/private_harvester.key"
  private_ssl_ca:
    crt: "config/ssl/ca/private_ca.crt"
    key: "config/ssl/ca/private_ca.key"
  salvia_ssl_ca:
    crt: "config/ssl/ca/salvia_ca.crt"
    key: "config/ssl/ca/salvia_ca.key"
pool:
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
farmer:
  port: 18523
  full_node_peer:
    host: *self_hostname
    port: 18520
  harvester_peer:
    host: *self_hostname
    port: 18524
  pool_public_keys: []
  start_rpc_server: True
  rpc_port: 18540
  pool_share_threshold: 1000
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  ssl:
    private_crt: "config/ssl/farmer/private_farmer.crt"
    private_key: "config/ssl/farmer/private_farmer.key"
    public_crt: "config/ssl/farmer/public_farmer.crt"
    public_key: "config/ssl/farmer/public_farmer.key"
timelord_launcher:
  host: *self_hostname
  port: 18500
  process_count: 3
  logging: *logging
timelord:
  port: 18522
  vdf_clients:
    ip:
    - *self_hostname
    - localhost
    - 127.0.0.1
    ips_estimate:
    - 150000
  full_node_peer:
    host: *self_hostname
    port: 18520
  max_connection_time: 60
  vdf_server:
    host: *self_hostname
    port: 18500
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  fast_algorithm: False
  sanitizer_mode: False
  ssl:
    private_crt: "config/ssl/timelord/private_timelord.crt"
    private_key: "config/ssl/timelord/private_timelord.key"
    public_crt: "config/ssl/timelord/public_timelord.crt"
    public_key: "config/ssl/timelord/public_timelord.key"
full_node:
  port: 18520
  db_sync: auto
  database_path: db/blockchain_v1_CHALLENGE.sqlite
  peer_db_path: db/peer_table_node.sqlite
  simulator_database_path: sim_db/simulator_blockchain_v1_CHALLENGE.sqlite
  simulator_peer_db_path: sim_db/peer_table_node.sqlite
  start_rpc_server: True
  rpc_port: 18530
  enable_upnp: True
  sync_blocks_behind_threshold: 300
  short_sync_blocks_behind_threshold: 20
  peer_connect_interval: 30
  peer_connect_timeout: 30
  target_peer_count: 80
  target_outbound_peer_count: 8
  exempt_peer_networks: []
  max_inbound_wallet: 20
  max_inbound_farmer: 10
  max_inbound_timelord: 5
  recent_peer_threshold: 6000
  send_uncompact_interval: 0
  target_uncompact_proofs: 100
  sanitize_weight_proof_only: False
  weight_proof_timeout: 360
  enable_profiler: False
  log_sqlite_cmds: False
  dns_servers:
  - "dns-introducer.salvianetwork.net"
  farmer_peer:
    host: *self_hostname
    port: 18523
  timelord_peer:
    host: *self_hostname
    port: 18522
  introducer_peer:
    host: introducer.salvianetwork.net
    port: 18520
  wallet_peer:
    host: *self_hostname
    port: 18525
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  ssl:
    private_crt: "config/ssl/full_node/private_full_node.crt"
    private_key: "config/ssl/full_node/private_full_node.key"
    public_crt: "config/ssl/full_node/public_full_node.crt"
    public_key: "config/ssl/full_node/public_full_node.key"
ui:
  port: 18510
  rpc_port: 18530
  ssh_filename: config/ssh_host_key
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  daemon_host: *self_hostname
  daemon_port: 18574
  daemon_ssl:
    private_crt: config/ssl/daemon/private_daemon.crt
    private_key: config/ssl/daemon/private_daemon.key
introducer:
  host: *self_hostname
  port: 18521
  max_peers_to_send: 20
  recent_peer_threshold: 6000
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  ssl:
    public_crt: "config/ssl/full_node/public_full_node.crt"
    public_key: "config/ssl/full_node/public_full_node.key"
wallet:
  port: 18525
  rpc_port: 18550
  enable_profiler: False
  db_sync: auto
  starting_height: 0
  start_height_buffer: 100
  num_sync_batches: 50
  initial_num_public_keys: 100
  initial_num_public_keys_new_wallet: 5
  full_node_peer:
    host: *self_hostname
    port: 18520
  testing: False
  database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  wallet_peers_path: wallet/db/wallet_peers.sqlite
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  target_peer_count: 5
  peer_connect_interval: 60
  recent_peer_threshold: 6000
  introducer_peer:
    host: introducer.salvianetwork.net
    port: 18520
  ssl:
    private_crt: "config/ssl/wallet/private_wallet.crt"
    private_key: "config/ssl/wallet/private_wallet.key"
    public_crt: "config/ssl/wallet/public_wallet.crt"
    public_key: "config/ssl/wallet/public_wallet.key"
  trusted_peers:
    trusted_node_1: "config/ssl/full_node/public_full_node.crt"
  short_sync_blocks_behind_threshold: 20
