name: Linux .rpm installer on Python 3.9

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Linux .rpm installer on Python 3.9
    runs-on: ubuntu-latest
    container:
      image: chianetwork/centos7-builder:latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Cancel previous runs on the same branch
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Cleanup any leftovers that exist from previous runs
      run: bash build_scripts/clean-runner.sh || true

    # Create our own venv outside of the git directory JUST for getting the ACTUAL version so that install can't break it
    - name: Get version number
      id: version_number
      run: |
        python3 -m venv ../venv
        . ../venv/bin/activate
        pip3 install setuptools_scm
        echo "::set-output name=SALVIA_INSTALLER_VERSION::$(python3 ./build_scripts/installer-version.py)"
        deactivate

    - name: Test for secrets access
      id: check_secrets
      shell: bash
      run: |
        unset HAS_SECRET
        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
        echo ::set-output name=HAS_SECRET::${HAS_SECRET}
      env:
        SECRET: "${{ secrets.INSTALLER_UPLOAD_SECRET }}"

    - name: Run install script
      env:
        INSTALL_PYTHON_VERSION: ${{ matrix.python-version }}
        BUILD_VDF_CLIENT: "N"
      run: |
        sh install.sh

    - name: Build .rpm package
      run: |
        . ./activate
        ldd --version
        cd ./salvia-blockchain-gui
        git status
        cd ../build_scripts
        sh build_linux_rpm.sh amd64

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Installers
        path: ${{ github.workspace }}/build_scripts/final_installer/

    - name: Create Checksums
      if: startsWith(github.ref, 'refs/tags/')
      env:
        SALVIA_INSTALLER_VERSION: ${{ steps.version_number.outputs.SALVIA_INSTALLER_VERSION }}
      run: |
         ls $GITHUB_WORKSPACE/build_scripts/final_installer/
         sha256sum $GITHUB_WORKSPACE/build_scripts/final_installer/salvia-blockchain-${{ steps.version_number.outputs.SALVIA_INSTALLER_VERSION }}-1.x86_64.rpm > $GITHUB_WORKSPACE/build_scripts/final_installer/salvia-blockchain-${{ steps.version_number.outputs.SALVIA_INSTALLER_VERSION }}-1.x86_64.rpm.sha256
         ls $GITHUB_WORKSPACE/build_scripts/final_installer/
         
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/build_scripts/final_installer/*.rpm*
        tag: ${{ steps.version_number.outputs.SALVIA_INSTALLER_VERSION }}
        overwrite: true
        file_glob: true